### ISSUE TITLE
Website URLs

### ISSUE THREAD

**Issue by KartikKannapur** [rohithpr/homepage#12]
Are you manually adding all the websites or do you have some way to automatically search them ?

**Comment by rohithpr** [comment]
Right now a bunch of them have been defined [here](https://github.com/rohithpr/bookmark-manager/blob/master/bm/app/predefined.py). These bookmarks will be added to every user at the time of signup. (Same as the ones shown in the [demo site](http://rohithpr.github.io/bookmark-manager/homepage.html).)

After this, the user can add new bookmarks using the form in the [edit page](http://rohithpr.github.io/bookmark-manager/edit.html). Click on the plus sign at the end of each category to unhide the form.

**Comment by rohithpr** [comment]
I didn't understand what you meant by "automatically search them".

**Comment by KartikKannapur** [comment]
I meant, it would be a better app if you gave the user an option to import bookmarks from chrome/firefox etc.

**Comment by rohithpr** [comment]
Hmmm... One way to do it be to ask the user to export the bookmarks as HTML, upload the file and scrape it here. I'll dig into it some more.

Any ideas on how to do it?

**Comment by KartikKannapur** [comment]
Have a look at it. There are many options.
I'll close this issue now.
