### ISSUE TITLE
Function of the Trash Button

### ISSUE THREAD

**Issue by KartikKannapur** [rohithpr/homepage#17]
What is the function of the 'Trash' button in the navbar ?

**Comment by rohithpr** [comment]
Bookmarks that have been deleted will be present there. Something like a recycle bin. From there you can either delete it permanently or restore it.

**Comment by KartikKannapur** [comment]
Okay, please add the functionality for the same then.

**Comment by sanjug** [comment]
Hey.It has already been implemented.
